'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {execFileSync}=require('node:child_process');
const os=require('node:os');
const path=require('node:path');
const output=fs.mkdtempSync(path.join(os.tmpdir(),'waar-legacy-test-'));
try{
 execFileSync('php',['bin/render-candidate-legacy-comparison.php',output],{stdio:'pipe'});
 const data=JSON.parse(fs.readFileSync(path.join(output,'comparison.json'),'utf8'));
 const template=fs.readFileSync('resources/candidate-legacy-comparison.html','utf8');
 const script=template.slice(template.lastIndexOf('<script>')+8,template.lastIndexOf('</script>'));
 function element(value=''){return {value,textContent:'',children:[],listeners:{},append(child){this.children.push(child);},replaceChildren(){this.children=[];},addEventListener(event,fn){this.listeners[event]=fn;}};}
 const elements=Object.fromEntries(['data','scenario','side','view','metric','chart','provenance','view-note','rows','count','error','scores','scenario-notes'].map(id=>[id,element()]));
 elements.data.textContent=JSON.stringify(data);
 elements.scenario.value=elements.side.value='all';elements.view.value='dilated';elements.metric.value='survivors';
 let option;
 vm.runInNewContext(script,{document:{getElementById:id=>elements[id],createElement:()=>element()},echarts:{init:()=>({setOption:next=>{option=next;},resize(){}})},window:{addEventListener(){}}});
 assert.equal(elements.rows.children.length,12);
 assert.equal(elements['scenario-notes'].children.length,6);
 assert.equal(elements['scenario-notes'].children[0].children[1].textContent,data.scenarioNotes[0].text);
 assert.match(template,/400 400 par camp/);
 assert.match(template,/parfois inégaux/);
 assert.equal(elements.rows.children[0].children[6].textContent,'+4,5');
 assert.equal(elements.rows.children[0].children[7].textContent,'-22,787');
 assert.match(option.series[1].tooltip.formatter(),/Δ victoire.*\+4,5 points/);
 assert.match(option.series[1].tooltip.formatter(),/Δ effectifs restants.*-22,787 points/);
 assert.equal(elements.scores.children.length,3);
 assert.equal(elements.scores.children[0].children[1].textContent,'100 / 100');
 assert.equal(elements.scores.children[1].children[1].textContent,'99,25 / 100');
 const globalScores=JSON.stringify(elements.scores.children);
 assert.equal(option.series.length,36);
 assert.equal(option.yAxis.min,-40);
 assert.equal(option.series[0].markLine.data[0][0].coord[1],data.rows[0].metrics.survivors.dilated.legacy[1]);
 elements.scenario.value='mixed-armies';elements.side.value='defender';elements.metric.value='economicValue';elements.metric.listeners.change();
 assert.equal(elements.rows.children.length,1);
 assert.equal(elements['scenario-notes'].children.length,1);
 assert.equal(elements['scenario-notes'].children[0].children[1].textContent,data.scenarioNotes[5].text);
 assert.equal(option.yAxis.min,-40);
 assert.ok(option.series[0].data[0][1]<-38);
 const survivorDelta=elements.rows.children[0].children[7].textContent;
 assert.equal(survivorDelta,data.rows[11].deltaPercentagePoints.survivorsDilated.toLocaleString('fr-FR',{maximumFractionDigits:3,signDisplay:'exceptZero'}));
 elements.view.value='raw';elements.view.listeners.change();
 assert.equal(option.yAxis.min,0);
 assert.equal(elements.rows.children[0].children[7].textContent,survivorDelta);
 assert.equal(JSON.stringify(elements.scores.children),globalScores);
 assert.equal(option.series[0].data[0][1],data.rows[11].metrics.economicValue.raw.legacy[1]);
 assert.equal(option.series[0].data[1][1],data.rows[11].metrics.economicValue.raw.candidate[1]);
 assert.throws(()=>execFileSync('php',['bin/render-candidate-legacy-comparison.php',output],{stdio:'pipe'}));
 console.log('candidate-legacy-comparison: ok (generation, controls, vectors, fixed axes, no overwrite)');
}finally{fs.rmSync(output,{recursive:true,force:true});}
