'use strict';
const assert=require('node:assert/strict');
require('../public/workshop/model.js');
const model=globalThis.WaarWorkshopModel;
assert.equal(model.cost({soldier:100,knight:2},{soldier:80,knight:350}),8700);
assert.equal(model.responseIsCurrent({requestId:'2'},2,'same','same'),true);
assert.equal(model.responseIsCurrent({requestId:'1'},2,'same','same'),false,'late response must be ignored');
assert.equal(model.responseIsCurrent({requestId:'2'},2,'old','new'),false,'response for edited configuration must be ignored');
assert.equal(model.stale('old','new'),true);
assert.equal(model.stale('same','same'),false);
console.log('workshop-model: ok');
const gate=model.createRevisionGate(),token=gate.capture('run');
assert.equal(gate.accept(token,'run'),true);
gate.invalidate();
assert.equal(gate.accept(token,'run'),false,'editing then reverting cannot revive a response');
assert.equal(gate.accept(gate.capture('run'),'other'),false);
const original={label:'Keep',combat:{capturePercent:9},weather:{rain:'.5'},relations:[1],units:{soldier:null}};
const prefilled=model.prefillUnits(original,{units:{soldier:{attack:'7'}}});
assert.equal(prefilled.label,'Keep');assert.deepEqual(prefilled.combat,original.combat);assert.deepEqual(prefilled.relations,original.relations);
assert.equal(original.units.soldier,null);assert.equal(prefilled.units.soldier.attack,'7');
const reference={rows:[{id:'a',winRate:.51,rawCasualtyRatio:.06}]};
const candidate={rows:[{id:'a',winRate:.8,rawCasualtyRatio:.04}]};
assert.deepEqual(model.plotRows(reference,candidate),[{id:'a',reference:{x:.51,y:.06},candidate:{x:.8,y:.04}}]);
assert.equal(model.stable({a:{b:1}})===model.stable({a:{b:2}}),false);
assert.deepEqual(model.boundedAppend([1,2],3,2),[2,3]);
assert.equal(model.measurementKey({b:2,a:1},'neutral'),model.measurementKey({a:1,b:2},'neutral'),'measurement cache keys are canonical');
assert.equal(model.retryDelay('3'),3000);
assert.equal(model.retryDelay('Wed, 21 Oct 2015 07:28:00 GMT',Date.parse('Wed, 21 Oct 2015 07:27:55 GMT')),5000);
(async()=>{const lane=model.createComputeLane();let release,entered=false;const first=lane.run(()=>new Promise(resolve=>release=resolve));const second=lane.run(()=>{entered=true;return 2});await Promise.resolve();assert.equal(entered,false);release();await first;assert.equal(await second,2);await assert.rejects(lane.run(()=>Promise.reject(new Error('failed'))));assert.equal(await lane.run(()=>3),3)})().catch(e=>{console.error(e);process.exitCode=1});
