'use strict';
const assert=require('node:assert/strict');
require('../public/workshop/model.js');
const model=globalThis.WaarWorkshopModel;
assert.equal(model.cost({soldier:100,knight:2},{soldier:80,knight:350}),8700);
assert.equal(model.responseIsCurrent({requestId:'2'},2,'same','same'),true);
assert.equal(model.responseIsCurrent({requestId:'1'},2,'same','same'),false,'late response must be ignored');
assert.equal(model.responseIsCurrent({requestId:'2'},2,'old','new'),false,'response for edited configuration must be ignored');
assert.equal(model.stale('old','new'),true);
assert.equal(model.stale('same','same'),false);
console.log('workshop-model: ok');
const gate=model.createRevisionGate(),token=gate.capture('run');
assert.equal(gate.accept(token,'run'),true);
gate.invalidate();
assert.equal(gate.accept(token,'run'),false,'editing then reverting cannot revive a response');
assert.equal(gate.accept(gate.capture('run'),'other'),false);
const original={label:'Keep',combat:{capturePercent:9},weather:{rain:'.5'},relations:[1],units:{soldier:null}};
const prefilled=model.prefillUnits(original,{units:{soldier:{attack:'7'}}});
assert.equal(prefilled.label,'Keep');assert.deepEqual(prefilled.combat,original.combat);assert.deepEqual(prefilled.relations,original.relations);
assert.equal(original.units.soldier,null);assert.equal(prefilled.units.soldier.attack,'7');
const reference={rows:[{id:'a',winRate:.51,appliedLossRatio:.06}]};
const candidate={rows:[{id:'a',winRate:.8,appliedLossRatio:.04}]};
assert.deepEqual(model.plotRows(reference,candidate),[{id:'a',reference:{x:.51,y:.06},candidate:{x:.8,y:.04}}]);
assert.equal(model.stable({a:{b:1}})===model.stable({a:{b:2}}),false);
